### ISSUE TITLE
failed to precompile / can't load package

### ISSUE THREAD

**Issue by fkastner** [JuliaGNI/StochasticIntegrators.jl#2]
Hi, 

I just found this package and noticed it errors if I try to install it.
Probably some things were not updated when you separated this from
GeometricIntegrators.jl.
Are you still planning to work on this package?

Greetings from Lübeck,
Felix

**Comment by michakraus** [comment]
Hi Felix,

Thanks a lot for the notification. That must have gone under the wheels.

I think I fixed all issues for now and made a new release which should be online anytime now. However, there is more refactoring to do. GeometricIntegrators underwent a lot of changes in the past year.

We are not very actively extending the package - functionality is added as needed - but we are definitely trying to maintain the package and refactor alongside the GeometricIntegrators development.

Greetings from Garching,
Michael

**Comment by fkastner** [comment]
Thanks for the quick response!
The package loads now and I also got it to simulate a simple SDE.
